version: '3.8'

services:
  php-fpm:
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html
    expose:
      - 9000

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  database:
    container_name: database
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=carreviews_user
      - POSTGRES_DB=carreviews

  symfony:
    container_name: symfony
    build:
      context: .
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  